#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-IO-Interactive
Version  : 1.022
Release  : 2
URL      : https://cpan.metacpan.org/authors/id/B/BD/BDFOY/IO-Interactive-1.022.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/B/BD/BDFOY/IO-Interactive-1.022.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libi/libio-interactive-perl/libio-interactive-perl_1.022-1.debian.tar.xz
Summary  : 'Utilities for interactive I/O'
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl Artistic-2.0 GPL-1.0
Requires: perl-IO-Interactive-license = %{version}-%{release}
BuildRequires : buildreq-cpan

%description
=pod
=encoding utf8
=head1 The IO::Interactive module
looking at this because you don't know where else to find what you're
looking for. Read this once and you might never have to read one again
for any Perl module.

%package dev
Summary: dev components for the perl-IO-Interactive package.
Group: Development
Provides: perl-IO-Interactive-devel = %{version}-%{release}

%description dev
dev components for the perl-IO-Interactive package.


%package license
Summary: license components for the perl-IO-Interactive package.
Group: Default

%description license
license components for the perl-IO-Interactive package.


%prep
%setup -q -n IO-Interactive-1.022
cd ..
%setup -q -T -D -n IO-Interactive-1.022 -b 1
mkdir -p deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/IO-Interactive-1.022/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-IO-Interactive
cp LICENSE %{buildroot}/usr/share/package-licenses/perl-IO-Interactive/LICENSE
cp deblicense/copyright %{buildroot}/usr/share/package-licenses/perl-IO-Interactive/deblicense_copyright
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/vendor_perl/5.26.1/IO/Interactive.pm

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/IO::Interactive.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/perl-IO-Interactive/LICENSE
/usr/share/package-licenses/perl-IO-Interactive/deblicense_copyright
